### ISSUE TITLE
How did you manage to get it to work with newer unity?

### ISSUE THREAD

**Issue by VladMarius** [catalincraciun/Chromacore#11]
Salut , am tot incercat sa rulez originalul (https://github.com/Murkantilism/game-off-2013) cu unity 4.6.8 si unity 5.2 (cu el primesc si mai multe erori , nu exista definitii pt. setTriangle si altceva de genu) , dar tot primesc eroarea : 

tk2d Undo/Redo callback failed. Undo/Redo not supported in this version of Unity.

UnityEngine.Debug:LogError(Object)

Doar asta primesc in unity 4.6.8, legat de libraria aia tk2d. 
Tu cum ai reusit sa o rezolvi?

Incerc si eu sa modific originalul,  in sensul meu dar nu pot sa rulez din cauza erorii . Cu 4.3 probabil merge, dar vers aia nu suporta noile platforme.

Toate bune.

Translation : How did you manage to get it to work with newer unity version? I always get the error in unity 4.6.8 and unity 5.2 (stated above)

**Comment by Murkantilism** [comment]
I am not familiar with the language you're speaking so I probably missed some details.

Anyway to your question "how did I get Chromacore working in Unity 5.2" is: I haven't. I have not worked on this game in roughly 2 years. It's not surprise that the version TK2D in my repository does not  work with 5.2. You likely need to update the plugin.

**Comment by VladMarius** [comment]
Hello Murkantilism, Marry Christmas and thanks for answering ! The question was more aimed at catalincraciun as he modded the game using a new unity version, but thanks for answering. I managed to get it working with the latest unity 4 version (released in dec 2015) . The problem is that i can only play and see only the MainLevel scene, cannot see main menu with level selector like in your vids or the touch controls on mobile. Am i doing something wrong?

**Comment by Murkantilism** [comment]
Ah snap didn't even realize this was someone else's repo, linking my repo sent me an email so I assumed it was my old repo, sorry my mistake. I'll take a look at how catal is upgrading the project to see if I can give you any advice

**Comment by VladMarius** [comment]
Well i solved the issue that i posted here about, in my second post i addressed the original version (yours), so i guess i should post this in your repo. Sorry about the hassle , i'm just curious about getting the extra stuff working (menu/levels/touch) , that i saw in your vid/pictures. I tried both repos  : https://github.com/Murkantilism/game-off-2013 and https://github.com/Murkantilism/Chromacore . I only found the MainLevel scene, nothing 'bout menu/levels etc.

**Comment by catalincraciun** [comment]
[Romanian]

Salut,

Pentru a il aduce la o versiune mai noua de Unity am facut schimbari radicale. Ei au folosit intial un engine pentru 2d, pe vremea cand Unity nu avea optiunea asta. Eu pur si simplu am eliminat libraria si rescris vreo 90% din cod. Daca mai ai si alte intrebari iti raspund cu placere. Cat despre repo-ul lor, nu stiu daca are rost sa iti pierzi timpul cu el, mai bine intelegi ce am facut eu.
