### ISSUE TITLE
Vre-un script pentru adaugare de culoare ?

### ISSUE THREAD

**Issue by VladMarius** [catalincraciun/Chromacore#12]
Salut, exista vre-un script sau metoda pt. adaugarea de culoare cand Teli prinde cate o sfera colorata?  Daca nu , in ce mod crezi ca as putea sa o adaug cat mai usor?

Toate bune.

**Comment by catalincraciun** [comment]
Salut, ei pur si simplu aveau incarcate obiecte cu diferite texturi colorate sau alb-negru. Noi am renuntat la partea de adaugare de culori si am lasat jocul alb-negru. Nu e un script pentru a schimba culori. Ti-as sugera ori sa creezi doua obiecte, unul colorat si unul alb-negru si pe unul sa il ascunzi si pe celalalt sa il arati cand vrei sa schimbi culoarea sau sa incerci sa schimbi textura direct pe un singur obiect, in runtime (a doua metoda e mai eficienta dpdv al memorie, dar nu chiar asa de simpla ca si prima)
